### ISSUE TITLE
開発メモ 2024-05-05

### ISSUE THREAD

**Issue by aoirint** [amaterusdb/amaterus_project#3]
- https://docs.google.com/document/d/1liwub4mktI1_HEfZf2EEMBFjHka6BeCyYqFxEZNGOQ0

**Comment by aoirint** [comment]
- Amaterus Crawler
  - 引数で有効化する機能を選択する
    - `python -m amaterus_crawler --target hoge,fuga`
    - `command: --target hoge,fuga`
    - Docker Compose
        ```yaml
        environment:
          - AMATERUS_CRAWLER_TARGET: hoge,fuga
        ```
    - tomlとかyamlで設定して設定ファイルを読ませる
        ```toml
        [crawler]
        [crawler.youtube_video_download]
        enabled = true
        ```
  - Amaterus Crawlerの責務
    - YouTubeから動画を見つける、DBに永続化
    - チャンネルから動画一覧を取得
      - ダウンロードすべき動画かどうかを判断
      - ダウンロード済みの動画かどうかを判断
    - YouTubeから動画をダウンロード、S3に永続化
- クロール結果をサイトにどう反映するか?
